FEAT: prettier config, precommit closes #30
ddal-kkak/ddal-kkak pull request #31
Opened 2024-04-16 15:24 UTC by eonnyhoney

### Changes
- package json scripts 와 lint-staged 동작에 prettier 를 추가
- lint 세팅 중 --max-warnings 0 때문에 제대로 동작하지 않아 해당 옵션을 삭제함 (@0r0loo 확인 plz 입니다)

### Screenshots

### Test Checklist
- 

### Link
- 테크스펙 :
- Figma :
- Ticket :
- 기타 :

2024-04-17 04:35 UTC, 0r0loo requested changes

2024-04-17 04:35 UTC, 0r0loo commented on packages/ui/package.json
> +    "lint": "eslint .",
정책을 어떻게 가져갈까요?

error 말고 warn 개수 지정하는건데, 걍 다풀면 warn 으로 통과되는게 많을 수도 있을것 같기도 하고요

의견 주세요

@KodywiththeK @eonnyhoney

2024-04-17 04:35 UTC, 0r0loo commented on .husky/pre-commit
> +pnpm lint-staged && git add .
add 는 하기 싫은것 까지 포함될 수 있어서 안하는게 좋지 않을까요?

2024-04-17 04:35 UTC, 0r0loo commented
prettier rc 파일도 추가 부탁드릴게요  🙏

2024-04-17 04:36 UTC, 0r0loo commented
p1 : PR 제목 변경 부탁드릴게요

2024-04-22 13:46 UTC, eonnyhoney commented on .husky/pre-commit
> +pnpm lint-staged && git add .
설득 완!

2024-04-22 13:46 UTC, eonnyhoney commented on packages/ui/package.json
> +    "lint": "eslint .",
요것도 일단 빡세게 가는 것에 설득되어 롤백해두었습니다!

2024-04-22 14:35 UTC, 0r0loo commented on packages/prettier-config/.prettierrc
> +}
```
{
  "tabWidth": 2,
  "printWidth": 80,
 }
```

얘도 추가해주실수있나요

2024-04-22 14:36 UTC, 0r0loo approved these changes

2024-04-25 12:59 UTC, merged