ddal-kkak 프로젝트 상대경로로 되어있는거 절대 경로로 수정
ddal-kkak/ddal-kkak pull request #46
Opened 2024-05-02 15:53 UTC by 0r0loo

### Changes
- tsconfig 절대경로로 import 되도록 수정했습니다.
- 만약 필요한 폴더가 있으면 이것처럼 보고 추가해주시면 됩니다.

### Screenshots

### Test Checklist
- 

### Link
- 테크스펙 :
- Figma :
- Ticket :
- 기타 :

2024-05-02 15:54 UTC, 0r0loo commented on apps/ddal-kkak/tsconfig.json
> +      "@/public/*": ["public/*"],
얘는 next 에서 import 방식이 다른가요? 아는사람 알려주세요

2024-05-03 00:31 UTC, KodywiththeK requested changes
"@/public/*": ["public/*"], 부분은 제거해주셔도 될듯합니다!

2024-05-03 00:31 UTC, KodywiththeK commented on apps/ddal-kkak/tsconfig.json
> +      "@/public/*": ["public/*"],
public 폴더는 빌드할때 루트경로로 옮겨진다고 알고있슴다.
따로 패스 설정하실 필요 없이, public 폴더 접근할 때는  아래처럼 URL 형식으로 접근하시면 됩니다.

- public/images/example.png (X)
- /images/example.png (O)

2024-05-04 04:41 UTC, 0r0loo commented on apps/ddal-kkak/tsconfig.json
> +      "@/public/*": ["public/*"],
수정완료

2024-05-04 08:28 UTC, eonnyhoney approved these changes

2024-05-04 08:50 UTC, KodywiththeK approved these changes

2024-05-04 08:51 UTC, merged