FEAT: 헤더 , 에디터페이지 레이아웃
ddal-kkak/ddal-kkak pull request #48
Opened 2024-05-03 00:10 UTC by KodywiththeK

### Changes
- 헤더 , 에디터페이지 레이아웃

### Screenshots

### Test Checklist
- 

### Link
- 테크스펙 :
- Figma :
- Ticket :
- 기타 :

2024-05-04 05:02 UTC, 0r0loo requested changes

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/__tests__/page.test.tsx
> +      name: /마케팅페이지 딸깍 하러가기/i,
ㅋㅋㅋ

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/app/edit/layout.tsx
> +type Props = {
type EditorLayoutProps = {} 로 부탁드릴게요

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/app/edit/layout.tsx
> +  children: React.ReactNode
children 의 경우 PropsWithChildren 을 사용해주세요

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/app/edit/layout.tsx
> +}
prettier 적용 안되는듯?

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/app/layout.tsx
>  }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/app/layout.tsx
> +const sans = Open_Sans({ subsets: ['latin'] })
우리 폰트 전부다 오픈산스로 갈껀가요?

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/app/page.tsx
> +      <div className="text-headline30 flex gap-2 items-center">
headline-30 으로 사용해주세요 그게 나을듯요  tailwind font 충돌때매요

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/ui/icons/IconClickFill.tsx
> +import { PiCursorClickFill } from 'react-icons/pi'
우리 lucid 폰트 쓰기로 하지 않았나요?

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/ui/icons/IconClickFill.tsx
> +  return <PiCursorClickFill className={className} />
text-2xl 을 유지하면서 className 을 확장하고 싶으시면

cn('text-2xl', className) 으로 해주세요

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/newFile.js
삭제해주세요

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/ui/HorizonLine.tsx
> +type Props = {
HorizonLineProps

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/ui/HorizonLine.tsx
> +  return <div className={`border-b border-b-grey-200 w-full ${className}`} />
cn('어쩌고', className)

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/editor/EditorComponents.tsx
> +]
이거 뭐뭐 할지 정해야할듯 그리고 여깄는걸 다쓰진 않을듯하네요

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/editor/EditorButtons.tsx
> +        <Button variant="outline" theme="secondary" className="w-full" size="lg">
button 에 full props 로 w-full 되는 거 하나 뚫어드릴게요

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/Footer.tsx
> +  return <p className="mt-10 bg-slate-900 py-4 text-center text-sm text-white">{`ⓒ ${new Date().getFullYear()} 딸깍 - All Right Reserved`}</p>
dayjs 받아서 쓰시죠

2024-05-04 05:02 UTC, 0r0loo commented on apps/ddal-kkak/components/Menu.tsx
> +}
이게 컴포넌트는 아닌것 같네요

2024-05-04 05:04 UTC, 0r0loo commented
하나의 PR 에 너무 많은 내용이 들어있는 것 같아요.

레이아웃이라고 해놓고 넘 많아요 내용이

그리고 아직 정하지 않은 내용들도 포함 되어있는 것 같습니다.

그리고 절대경로 PR 머지되면 Rebase 하신다음 import 된거 다 절대경로로 변경해주세요

2024-05-04 05:04 UTC, 0r0loo commented on apps/ddal-kkak/app/layout.tsx
> +        <link rel="icon" href="./favicon.ico" type="image/x-icon" sizes="any" />
이거 설정안해도 favicon 인식하지 않나요?

2024-05-04 05:05 UTC, 0r0loo commented on apps/ddal-kkak/app/layout.tsx
> +      </body>
root 랑 body 에 너무 많은 css 를 넣으신 것 같아요
그리고 html, body 는  여기에서 tailwind 로 하지말고 global 에서 관리하는게 좋을듯합니다

2024-05-04 05:07 UTC, 0r0loo commented on apps/ddal-kkak/app/layout.tsx
> +import { Metadata } from 'next/dist/lib/metadata/types/metadata-interface'
🙋‍♀️ 얘는 경로가 이렇게 import 되나요?

2024-05-04 05:10 UTC, 0r0loo commented on apps/ddal-kkak/components/Header.tsx
> +                        {isClicked(pathname) ? clickedIcon : icon}
ex)
<Icon pathname=pathname />

이렇게 했을 때 

Icon 컴포넌트에서 알아서 ClickedIcon Icon 골라서 렌더링해주는게 더 좋아보이네요

2024-05-10 09:56 UTC, KodywiththeK commented on apps/ddal-kkak/components/Menu.tsx
> +}
흐음 이런건 컴포넌트 외에 어떤 폴더를 만들어서 넣는게 좋을까요?

2024-05-10 10:08 UTC, KodywiththeK commented on apps/ddal-kkak/app/edit/layout.tsx
> +  children: React.ReactNode
Props => EditorLayoutProps
children => PropsWithChildren 으로 변경하라는 말씀이실까요?

아님 children이 있는 Props 이름은 PropsWithChildren으로 하라는 말씀이실까요

2024-05-13 13:18 UTC, 0r0loo approved these changes

2024-05-13 13:18 UTC, merged